"""Centralised prompt templates for the Delve AI assistant."""

from .system import DEFAULT_SYSTEM_PROMPT
from .router import ROUTER_SYSTEM_PROMPT, ROUTER_HUMAN_PROMPT
from .sequential_planner import SEQUENTIAL_PLANNER_SYSTEM_PROMPT, SEQUENTIAL_PLANNER_HUMAN_PROMPT
from .sequential_executor import SEQUENTIAL_EXECUTOR_SYSTEM_PROMPT, SEQUENTIAL_EXECUTOR_HUMAN_PROMPT

__all__ = [
    "DEFAULT_SYSTEM_PROMPT",
    "ROUTER_SYSTEM_PROMPT",
    "ROUTER_HUMAN_PROMPT",
    "SEQUENTIAL_PLANNER_SYSTEM_PROMPT",
    "SEQUENTIAL_PLANNER_HUMAN_PROMPT",
    "SEQUENTIAL_EXECUTOR_SYSTEM_PROMPT",
    "SEQUENTIAL_EXECUTOR_HUMAN_PROMPT",
]